version: "3.7"

services:
  flask:
    build:
      context: ./flask
      dockerfile: ../Dockerfile-dev
    container_name: flask
    environment:
      - APP_NAME=FlaskApp
      - FLASK_APP=main.py
      - FLASK_ENV=testing
      - FLASK_DEBUG=true
      - SECRET_KEY='SOME RANDOM FOR DEVELOPMENT AND TESTING'
      # CELERY_RDB_HOST default is localhost
      # to allow RDB able to be connected outside the container CELERY_RDB_HOST
      # is needed to be something else rather than localhost
      - CELERY_RDB_HOST=0.0.0.0
    ports:
      # default debugging port of celery 4.4.7 is 6900 according to official
      # doc, however the port differs very often and CELERY_RDB_PORT does not
      # take effect.
      #
      # in my case it is usally 6906, and then 6907
      - "6900-6910:6900-6910"
      - "5555:5555"
    expose:
      - 8080
    depends_on:
      - redis
    volumes:
      - ./flask:/app
    entrypoint: /docker-entrypoint.sh
    command: uwsgi app.ini

  nginx:
    build: ./nginx
    container_name: nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

  redis:
    image: "redis:alpine"
    container_name: redis_article
    expose: 
      - 6379

